### ISSUE TITLE
Save imported Step-File

### ISSUE THREAD

**Issue by HelmutMelmer** [koechlm/VDS-Sample-Configurations-2025#4]
Hello Markus,

When importing a step file, I noticed that with VDS standard, the data sheet appears when saving. With your "VDS-MFG-Sample" inventor only saves. Is that a mistake or is that how it is intended? I made two videos.

Many thanks

Regards

Helmut Melmer

https://github.com/user-attachments/assets/21862570-2403-4a49-9a4b-b00f8c6940ce
https://github.com/user-attachments/assets/3e8393de-cc8a-49c1-a733-fb653967436e

**Comment by koechlm** [comment]
Hi Helmut,
It is intended, and you can easily change the behavior (aligned to default): remove the "Sending System" property from the configuration (https://github.com/koechlm/VDS-Sample-Configurations-2025/blob/master/VDS-MFG-Sample-CAD/CAD.Custom/Configuration/Inventor.cfg#L15), and you are all set to get a VDS dialog for each STEP component. Be aware that you might get hundreds of save file dialogs then...

**Comment by HelmutMelmer** [comment]
Hello Markus,

it worked!

Thank you very much
